//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.04 at 06:29:19 PM MSD 
//


package com.sun.electric.technology.jaxb;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for NodeLayerStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NodeLayerStyle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FILLED"/>
 *     &lt;enumeration value="CLOSED"/>
 *     &lt;enumeration value="CROSSED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum NodeLayerStyle {

    FILLED,
    CLOSED,
    CROSSED;

    public String value() {
        return name();
    }

    public static NodeLayerStyle fromValue(String v) {
        return valueOf(v);
    }

}
